### PR TITLE
Docs: Fix URI for must-gather image

### PR DESCRIPTION
**Pull request by yuumasato**
The `must-gather` image's name is `must-gather-ocp`.

See https://github.com/orgs/ComplianceAsCode/packages?repo_name=compliance-operator

### CODE REVIEW

**Comment by rhmdnd** [comment]
Does this need a rebase to pick up a fix for e2e to pass?

**Comment by rhmdnd** [comment]
Also - this is a docs only change so it should be excluded from e2e tests since we recently landed a change to skip e2e tests for doc changes.

https://github.com/openshift/release/pull/42834

**Comment by BhargaviGudi** [comment]
label /qe-approved
<pre>
$ oc adm must-gather --image=ghcr.io/complianceascode/must-gather-ocp:latest
[must-gather      ] OUT Using must-gather plug-in image: ghcr.io/complianceascode/must-gather-ocp:latest
When opening a support case, bugzilla, or issue please include the following summary data along with any other requested information:
ClusterID: d23b87b3-b1b5-4ad7-91fd-401e6709061c
ClusterVersion: Stable at "4.14.0-0.nightly-2023-10-08-220853"
ClusterOperators:
	All healthy and stable


[must-gather      ] OUT namespace/openshift-must-gather-nrfv9 created
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-r4vgz created
[must-gather      ] OUT pod for plug-in image ghcr.io/complianceascode/must-gather-ocp:latest created
[must-gather-qcqlr] POD 2023-10-10T07:52:02.389353988Z + COMPONENT=compliance
[must-gather-qcqlr] POD 2023-10-10T07:52:02.389353988Z + BIN=oc
[must-gather-qcqlr] POD 2023-10-10T07:52:02.389353988Z + LOGS_DIR=/must-gather
[must-gather-qcqlr] POD 2023-10-10T07:52:02.390122269Z ++ oc get crds -o 'jsonpath={.items[*].metadata.name}'
[must-gather-qcqlr] POD 2023-10-10T07:52:02.390283065Z ++ tr ' ' '\n'
[must-gather-qcqlr] POD 2023-10-10T07:52:02.390482560Z ++ grep compliance
[must-gather-qcqlr] POD 2023-10-10T07:52:03.482947009Z + APIRESOURCES=
[must-gather-qcqlr] POD 2023-10-10T07:52:03.483021207Z + NAMESPACES=(openshift-compliance)
[must-gather-qcqlr] POD 2023-10-10T07:52:03.483048206Z + APIRESOURCES=(configmaps pods routes roles rolebindings serviceaccounts services leases)
[must-gather-qcqlr] POD 2023-10-10T07:52:03.483129004Z + for NAMESPACE in ${NAMESPACES[@]}
[must-gather-qcqlr] POD 2023-10-10T07:52:03.483603693Z ++ oc get pods -n openshift-compliance -o 'jsonpath={.items[*].metadata.name}'
[must-gather-qcqlr] POD 2023-10-10T07:52:03.611847352Z + PODS=
[must-gather-qcqlr] POD 2023-10-10T07:52:03.611925950Z + mkdir -p /must-gather/openshift-compliance/pods
[must-gather-qcqlr] POD 2023-10-10T07:52:03.614617884Z + for APIRESOURCE in ${APIRESOURCES[@]}
[must-gather-qcqlr] POD 2023-10-10T07:52:03.614617884Z + mkdir -p /must-gather/openshift-compliance/configmaps
[must-gather-qcqlr] POD 2023-10-10T07:52:03.616602436Z + oc describe configmaps -n openshift-compliance
[must-gather-qcqlr] POD 2023-10-10T07:52:03.738688046Z No resources found in openshift-compliance namespace.
[must-gather-qcqlr] POD 2023-10-10T07:52:03.742335857Z + oc get configmaps -n openshift-compliance -o=yaml
[must-gather-qcqlr] POD 2023-10-10T07:52:03.882199532Z + for APIRESOURCE in ${APIRESOURCES[@]}
[must-gather-qcqlr] POD 2023-10-10T07:52:03.882199532Z + mkdir -p /must-gather/openshift-compliance/pods
[must-gather-qcqlr] POD 2023-10-10T07:52:03.885085261Z + oc describe pods -n openshift-compliance
[must-gather-qcqlr] POD 2023-10-10T07:52:04.018619491Z No resources found in openshift-compliance namespace.
[must-gather-qcqlr] POD 2023-10-10T07:52:04.021580319Z + oc get pods -n openshift-compliance -o=yaml
[must-gather-qcqlr] POD 2023-10-10T07:52:04.166545069Z + for APIRESOURCE in ${APIRESOURCES[@]}
[must-gather-qcqlr] POD 2023-10-10T07:52:04.166545069Z + mkdir -p /must-gather/openshift-compliance/routes
[must-gather-qcqlr] POD 2023-10-10T07:52:04.169632893Z + oc describe routes -n openshift-compliance
[must-gather-qcqlr] POD 2023-10-10T07:52:04.315245228Z No resources found in openshift-compliance namespace.
[must-gather-qcqlr] POD 2023-10-10T07:52:04.318349552Z + oc get routes -n openshift-compliance -o=yaml
[must-gather-qcqlr] POD 2023-10-10T07:52:04.480217788Z + for APIRESOURCE in ${APIRESOURCES[@]}
[must-gather-qcqlr] POD 2023-10-10T07:52:04.480217788Z + mkdir -p /must-gather/openshift-compliance/roles
[must-gather-qcqlr] POD 2023-10-10T07:52:04.483080018Z + oc describe roles -n openshift-compliance
[must-gather-qcqlr] POD 2023-10-10T07:52:04.604754338Z No resources found in openshift-compliance namespace.
[must-gather-qcqlr] POD 2023-10-10T07:52:04.607284976Z + oc get roles -n openshift-compliance -o=yaml
[must-gather-qcqlr] POD 2023-10-10T07:52:04.734305066Z + for APIRESOURCE in ${APIRESOURCES[@]}
[must-gather-qcqlr] POD 2023-10-10T07:52:04.734305066Z + mkdir -p /must-gather/openshift-compliance/rolebindings
[must-gather-qcqlr] POD 2023-10-10T07:52:04.737393790Z + oc describe rolebindings -n openshift-compliance
[must-gather-qcqlr] POD 2023-10-10T07:52:04.856734968Z No resources found in openshift-compliance namespace.
[must-gather-qcqlr] POD 2023-10-10T07:52:04.859558699Z + oc get rolebindings -n openshift-compliance -o=yaml
[must-gather-qcqlr] POD 2023-10-10T07:52:04.992704339Z + for APIRESOURCE in ${APIRESOURCES[@]}
[must-gather-qcqlr] POD 2023-10-10T07:52:04.992704339Z + mkdir -p /must-gather/openshift-compliance/serviceaccounts
[must-gather-qcqlr] POD 2023-10-10T07:52:04.995101180Z + oc describe serviceaccounts -n openshift-compliance
[must-gather-qcqlr] POD 2023-10-10T07:52:05.149185407Z No resources found in openshift-compliance namespace.
[must-gather-qcqlr] POD 2023-10-10T07:52:05.152241232Z + oc get serviceaccounts -n openshift-compliance -o=yaml
[must-gather-qcqlr] POD 2023-10-10T07:52:05.286770938Z + for APIRESOURCE in ${APIRESOURCES[@]}
[must-gather-qcqlr] POD 2023-10-10T07:52:05.286770938Z + mkdir -p /must-gather/openshift-compliance/services
[must-gather-qcqlr] POD 2023-10-10T07:52:05.289436372Z + oc describe services -n openshift-compliance
[must-gather-qcqlr] POD 2023-10-10T07:52:05.411397086Z No resources found in openshift-compliance namespace.
[must-gather-qcqlr] POD 2023-10-10T07:52:05.414423912Z + oc get services -n openshift-compliance -o=yaml
[must-gather-qcqlr] POD 2023-10-10T07:52:05.541364303Z + for APIRESOURCE in ${APIRESOURCES[@]}
[must-gather-qcqlr] POD 2023-10-10T07:52:05.541467801Z + mkdir -p /must-gather/openshift-compliance/leases
[must-gather-qcqlr] POD 2023-10-10T07:52:05.543753645Z + oc describe leases -n openshift-compliance
[must-gather-qcqlr] POD 2023-10-10T07:52:05.660373810Z No resources found in openshift-compliance namespace.
[must-gather-qcqlr] POD 2023-10-10T07:52:05.662832210Z + oc get leases -n openshift-compliance -o=yaml
[must-gather-qcqlr] POD 2023-10-10T07:52:05.793880836Z + KEY=compliance
[must-gather-qcqlr] POD 2023-10-10T07:52:05.793880836Z + NAMESPACE=openshift-compliance
[must-gather-qcqlr] POD 2023-10-10T07:52:05.793880836Z + APIRESOURCES=(clusterroles clusterrolebindings)
[must-gather-qcqlr] POD 2023-10-10T07:52:05.793959036Z + for APIRESOURCE in ${APIRESOURCES[@]}
[must-gather-qcqlr] POD 2023-10-10T07:52:05.794784036Z ++ oc get clusterroles -o 'jsonpath={.items[*].metadata.name}'
[must-gather-qcqlr] POD 2023-10-10T07:52:05.794897136Z ++ tr ' ' '\n'
[must-gather-qcqlr] POD 2023-10-10T07:52:05.795212837Z ++ grep compliance
[must-gather-qcqlr] POD 2023-10-10T07:52:06.108237598Z + NAMES=
[must-gather-qcqlr] POD 2023-10-10T07:52:06.108237598Z + for APIRESOURCE in ${APIRESOURCES[@]}
[must-gather-qcqlr] POD 2023-10-10T07:52:06.109040198Z ++ oc get clusterrolebindings -o 'jsonpath={.items[*].metadata.name}'
[must-gather-qcqlr] POD 2023-10-10T07:52:06.109203098Z ++ tr ' ' '\n'
[must-gather-qcqlr] POD 2023-10-10T07:52:06.109436498Z ++ grep compliance
[must-gather-qcqlr] POD 2023-10-10T07:52:06.379030652Z + NAMES=
[must-gather-qcqlr] POD 2023-10-10T07:52:06.379708852Z ++ oc get pods -n openshift-compliance -o 'jsonpath={.items[*].metadata.name}'
[must-gather-qcqlr] POD 2023-10-10T07:52:06.379818752Z ++ tr ' ' '\n'
[must-gather-qcqlr] POD 2023-10-10T07:52:06.380058152Z ++ grep compliance
[must-gather-qcqlr] POD 2023-10-10T07:52:06.543228784Z + PODS=
[must-gather-qcqlr] POD 2023-10-10T07:52:06.543265884Z + mkdir -p /must-gather/openshift-compliance/pods
[must-gather-qcqlr] OUT waiting for gather to complete
[must-gather-qcqlr] OUT downloading gather output
[must-gather-qcqlr] OUT receiving incremental file list
[must-gather-qcqlr] OUT ./
[must-gather-qcqlr] OUT openshift-compliance/
[must-gather-qcqlr] OUT openshift-compliance/configmaps/
[must-gather-qcqlr] OUT openshift-compliance/configmaps/describe.log
[must-gather-qcqlr] OUT openshift-compliance/configmaps/get.yaml
[must-gather-qcqlr] OUT openshift-compliance/leases/
[must-gather-qcqlr] OUT openshift-compliance/leases/describe.log
[must-gather-qcqlr] OUT openshift-compliance/leases/get.yaml
[must-gather-qcqlr] OUT openshift-compliance/pods/
[must-gather-qcqlr] OUT openshift-compliance/pods/describe.log
[must-gather-qcqlr] OUT openshift-compliance/pods/get.yaml
[must-gather-qcqlr] OUT openshift-compliance/rolebindings/
[must-gather-qcqlr] OUT openshift-compliance/rolebindings/describe.log
[must-gather-qcqlr] OUT openshift-compliance/rolebindings/get.yaml
[must-gather-qcqlr] OUT openshift-compliance/roles/
[must-gather-qcqlr] OUT openshift-compliance/roles/describe.log
[must-gather-qcqlr] OUT openshift-compliance/roles/get.yaml
[must-gather-qcqlr] OUT openshift-compliance/routes/
[must-gather-qcqlr] OUT openshift-compliance/routes/describe.log
[must-gather-qcqlr] OUT openshift-compliance/routes/get.yaml
[must-gather-qcqlr] OUT openshift-compliance/serviceaccounts/
[must-gather-qcqlr] OUT openshift-compliance/serviceaccounts/describe.log
[must-gather-qcqlr] OUT openshift-compliance/serviceaccounts/get.yaml
[must-gather-qcqlr] OUT openshift-compliance/services/
[must-gather-qcqlr] OUT openshift-compliance/services/describe.log
[must-gather-qcqlr] OUT openshift-compliance/services/get.yaml
[must-gather-qcqlr] OUT 
[must-gather-qcqlr] OUT sent 371 bytes  received 1,850 bytes  493.56 bytes/sec
[must-gather-qcqlr] OUT total size is 544  speedup is 0.24
[must-gather      ] OUT namespace/openshift-must-gather-nrfv9 deleted
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-r4vgz deleted


Reprinting Cluster State:
When opening a support case, bugzilla, or issue please include the following summary data along with any other requested information:
ClusterID: d23b87b3-b1b5-4ad7-91fd-401e6709061c
ClusterVersion: Stable at "4.14.0-0.nightly-2023-10-08-220853"
ClusterOperators:
	All healthy and stable
</pre>

**Review by rhmdnd — APPROVED** [review]
/lgtm

**Pull request merged**
