### PR TITLE
Refactor helm installs

### PR DESCRIPTION
**Pull request by rhmdnd**
We recently landed a change to bump the operator-sdk version, which
resulted in breaking apart the roles and cluster roles for the
compliance operator into separate files.

This commit updates the Helm installation documentation and links to
work with the new location after the operator-sdk update.

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]

**Comment by xiaojiey** [comment]
@rhmdnd I am not sure with the test procedure. Correct me if I am wrong.
Seems installation succeed. But the suite will return error. Details seen from: https://privatebin.corp.redhat.com/?21c8e41fceaeb256#EMVPWyjUcwUQaFfrYSvoBiSuMeJMtsa9C8trJtaQ68pp

**Comment by rhmdnd** [comment]
> @rhmdnd I am not sure about the test procedure. Correct me if I am wrong.
> Seems installation succeed. But the suite will return error. Details seen from: https://privatebin.corp.redhat.com/?21c8e41fceaeb256#EMVPWyjUcwUQaFfrYSvoBiSuMeJMtsa9C8trJtaQ68pp

I believe the issues you're hitting is unrelated and it's currently being addressed in the CaC/content repository.

https://github.com/ComplianceAsCode/content/pull/9435 contains some context from @jhrozek. A separate fix just landed https://github.com/ComplianceAsCode/content/pull/9436

**Pull request merged**
