### PR TITLE
Add Start and End time to CRD

### PR DESCRIPTION
**Pull request by Vincent056**
Added a StartTimestamp and EndTimestamp field to the ComplianceScan CRD

### CODE REVIEW

**Review by jhrozek — APPROVED** [review]
/lgtm

**Review by JAORMX — APPROVED** [review]
/lgtm
/approve

**Comment by jhrozek** [comment]
@Vincent056 could you please chase down the acks so that we can merge the PR?
@mkumku PTAL for px-ack
@sheriff-rh PTAL for doc-ack

**Comment by sheriff-rh** [comment]
LGTM!

**Review by jhrozek — APPROVED** [review]
/lgtm

**Pull request merged**
