### PR TITLE
bug 2098581: Don't import batchv1beta1 anymore

### PR DESCRIPTION
**Pull request by jhrozek**
Let's stop using deprecated interfaces.

Resolves: rhbz#2098581

### CODE REVIEW

**Comment by xiaojiey** [comment]
With this PR, the APIRemovedInNextEUSReleaseInUse alert won't fired for openshift-compliance cronjobs
```
$ oc get clusterversion
NAME      VERSION                              AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.12.0-0.nightly-2022-09-25-071630   True        False         11h     Cluster version is 4.12.0-0.nightly-2022-09-25-071630
$ oc get pod
NAME                                              READY   STATUS    RESTARTS        AGE
compliance-operator-d47877fbd-4db77               1/1     Running   1 (6m25s ago)   6m33s
ocp4-openshift-compliance-pp-7cb94bcdc6-nhjwj     1/1     Running   0               6m13s
rhcos4-openshift-compliance-pp-67c79bc97b-4qtl4   1/1     Running   0               6m13s
$ token=`oc  create token prometheus-k8s -n openshift-monitoring`
$ oc -n openshift-compliance exec compliance-operator-d47877fbd-4db77  -- curl -k -H "Authorization: Bearer $token" 'https://prometheus-k8s.openshift-monitoring.svc:9091/api/v1/query?' --data-urlencode 'query=ALERTS{alertname="APIRemovedInNextEUSReleaseInUse",resource="cronjobs"}' | jq
time="2022-09-26T13:17:59Z" level=error msg="exec failed: unable to start container process: exec: \"curl\": executable file not found in $PATH"
command terminated with exit code 255
```

**Comment by jhrozek** [comment]
I just added a changelog item for both this change and also for PR #141. No other changes.

**Pull request merged**
