### PR TITLE
Release v0.1.58

### PR DESCRIPTION
**Pull request by rhmdnd**

### CODE REVIEW

**Comment by mrogers950** [comment]
e2e failed on two of the parallel tests TestCheckDefaultKubeletConfig and TestManualRulesTailoredProfile https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/ComplianceAsCode_compliance-operator/181/pull-ci-ComplianceAsCode-compliance-operator-master-e2e-aws/1592558039989227520/artifacts/e2e-aws/test/build-log.txt
```
    helpers.go:711: 2022-11-15T18:04:39Z: Waiting for availability of manual-rules-test-node compliancesuite
=== CONT  TestE2E/Parallel_tests/TestCheckDefaultKubeletConfig
    helpers.go:711: 2022-11-15T18:04:44Z: Waiting for availability of kubelet-default-test-suite compliancesuite
=== CONT  TestE2E/Parallel_tests/TestManualRulesTailoredProfile
    helpers.go:711: 2022-11-15T18:04:44Z: Waiting for availability of manual-rules-test-node compliancesuite
=== CONT  TestE2E/Parallel_tests/TestCheckDefaultKubeletConfig
    helpers.go:711: 2022-11-15T18:04:49Z: Waiting for availability of kubelet-default-test-suite compliancesuite
=== CONT  TestE2E/Parallel_tests/TestManualRulesTailoredProfile
    helpers.go:711: 2022-11-15T18:04:49Z: Waiting for availability of manual-rules-test-node compliancesuite
=== CONT  TestE2E/Parallel_tests/TestCheckDefaultKubeletConfig
    helpers.go:711: 2022-11-15T18:04:54Z: Waiting for availability of kubelet-default-test-suite compliancesuite
=== CONT  TestE2E/Parallel_tests/TestManualRulesTailoredProfile
    helpers.go:711: 2022-11-15T18:04:54Z: Waiting for availability of manual-rules-test-node compliancesuite
=== CONT  TestE2E/Parallel_tests/TestCheckDefaultKubeletConfig
    helpers.go:711: 2022-11-15T18:04:59Z: Waiting for availability of kubelet-default-test-suite compliancesuite
=== CONT  TestE2E/Parallel_tests/TestManualRulesTailoredProfile
    helpers.go:711: 2022-11-15T18:04:59Z: Waiting for availability of manual-rules-test-node compliancesuite
    helpers.go:711: 2022-11-15T18:04:59Z: Waiting for availability of manual-rules-test-node compliancesuite
    helpers.go:298: compliancesuites.compliance.openshift.io "manual-rules-test-node" not found
=== CONT  TestE2E/Parallel_tests/TestCheckDefaultKubeletConfig
    helpers.go:711: 2022-11-15T18:05:04Z: Waiting for availability of kubelet-default-test-suite compliancesuite
    helpers.go:711: 2022-11-15T18:05:09Z: Waiting for availability of kubelet-default-test-suite compliancesuite
    helpers.go:711: 2022-11-15T18:05:14Z: Waiting for availability of kubelet-default-test-suite compliancesuite
    helpers.go:711: 2022-11-15T18:05:14Z: Waiting for availability of kubelet-default-test-suite compliancesuite
    helpers.go:298: compliancesuites.compliance.openshift.io "kubelet-default-test-suite" not found

```

**Comment by mrogers950** [comment]
/retest

Retesting to see if the above failure is chronic

**Comment by rhmdnd** [comment]
> Retesting to see if the above failure is chronic

I dug through the logs but I couldn't find a clear cause.

Thanks for rechecking.

**Review by Vincent056 — APPROVED** [review]

**Comment by Vincent056** [comment]
Adding px,qe,doc labels since it will not be released downstream

**Pull request merged**
