### PR TITLE
Bug 2088202: Adjust the namespace for the restricted Pod Security Admission

### PR DESCRIPTION
**Pull request by jhrozek**
The PR contains two patches:

1. deploy: Label the operator namespace so that the privileged Pod Security Admission can be used
On clusters where Pod Security Admission is used and the restricted profile
is used by default, namespaces where privileged workloads are running must
be labeled with the appropriate pod-security.kubernetes.io/XXX:YYY labels
to allow privileged execution.

2. deploy: Tighten operator securityContext
- makes the operator and some workloads run as non root explicitly
- drops all caps where appropriate

### CODE REVIEW

**Comment by jhrozek** [comment]
/hold
so that @xiaojiey has a chance to test

**Comment by jhrozek** [comment]
/hold cancel
because the testing went well

**Comment by jhrozek** [comment]
The new version just adds CHANGELOG entries.

**Review by Vincent056 — APPROVED** [review]
/lgtm

**Pull request merged**
