### PR TITLE
Add HyperShift usage doc

### PR DESCRIPTION
**Pull request by Vincent056**
Added documentation on how to run a scan on HyperShift Management Cluster

### CODE REVIEW

**Comment by Vincent056** [comment]
This usage doc works with https://github.com/ComplianceAsCode/compliance-operator/pull/235 and https://github.com/ComplianceAsCode/content/pull/10333

**Review by jhrozek — APPROVED** [review]
/lgtm
the technical content is good, let's have @sheriff-rh review the language aspect

**Comment by rhmdnd** [comment]
> Docs LGTM! Is this expected to land in 1.0.0?

This will likely be after 1.0.0 since 1.0.0 will be pretty much the same code as 0.1.61.

**Comment by jhrozek** [comment]
@Vincent056 can you rebase again? I'll lgtm once the PR applies cleanly atop master..

**Review by jhrozek — APPROVED** [review]
/lgtm

**Review by jhrozek — APPROVED** [review]
/lgtm

**Pull request merged**
