### PR TITLE
Fix test_broken_content github action

### PR DESCRIPTION
**Pull request by Vincent056**
This pr is to fix the workflow for building test_broken_content github action.

### CODE REVIEW

**Comment by jhrozek** [comment]
timeout..
/retest

**Comment by jhrozek** [comment]
lol I looked at CI status before I looked at the commit
let's explicit add a 
/hold
so the PR does not get merged

**Comment by Vincent056** [comment]
cancel /hold

**Comment by rhmdnd** [comment]
We should be able to rebased this and pickup https://github.com/ComplianceAsCode/compliance-operator/pull/277 to fix the parallel tests.

**Comment by rhmdnd** [comment]
I wonder if we have an issue with `TestScanSettingBindingWatchesTailoredProfile`. It's failed a few times now, but it's not blocking CI.

```
 === CONT  TestE2E/Parallel_tests/TestScanSettingBindingWatchesTailoredProfile
    helpers.go:297: expected the TP to be created with an error 
```

**Comment by Vincent056** [comment]
rebased again to see if that solve the issue

**Comment by JAORMX** [comment]
Oh, sorry that metal-toolbox/container-push/.github/workflows/container-push.yml hasn't worked as expected. Got any more details on what's not working there?

**Comment by Vincent056** [comment]
> Oh, sorry that metal-toolbox/container-push/.github/workflows/container-push.yml hasn't worked as expected. Got any more details on what's not working there?

Thanks for checking in,
I think everything should be fixed now with the metal-toolbox/container-push/.github/workflows/container-push.yml

**Review by jhrozek — APPROVED** [review]
/lgtm

**Pull request merged**
