### PR TITLE
Release v0.1.60

### PR DESCRIPTION
**Pull request by rhmdnd**

### CODE REVIEW

**Review by Vincent056 — APPROVED** [review]
/lgtm

**Comment by jhrozek** [comment]
see PR #203 - that should make the CVE scanner happy and if it does, that PR should go first and then we should rebase atop that.

**Comment by jhrozek** [comment]
retesting won't help, we need to merge PR #203 first and rebase atop that...

**Comment by rhmdnd** [comment]
Rebased to pull in the changes Jakub proposed.

**Review by JAORMX — APPROVED** [review]

**Comment by sheriff-rh** [comment]
lgtm! :rocket:

**Comment by rhmdnd** [comment]
/label qe-approved

Adding the QE label since @xiaojiey approved all relevant PRs delivered in this release.

**Pull request merged**
