### PR TITLE
:broom: remove downstream-specific Dockerfile

### PR DESCRIPTION
**Pull request by rhmdnd**
We maintain three different Dockerfiles for similar purposes. One for CI
called `Dockerfile.ci`, another for downstream builds called
`Dockerfile.ocp`, and another in build/Dockerfile.

The downstream Dockerfile isn't used anywhere, so let's remove it so we
have less places to update golang versions.

### CODE REVIEW

**Comment by rhmdnd** [comment]
Hold until we get good testing signal.

**Comment by Vincent056** [comment]
rosa failures looks unrelated

/lgtm

**Comment by rhmdnd** [comment]
/test e2e-rosa

failed to provision the rosa cluster - unrelated to this change.

**Comment by rhmdnd** [comment]
/test e2e-rosa

Another unrelated failure due to the rosa cluster failing to install.

**Comment by rhmdnd** [comment]
Fixed up the remove conflict. @Vincent056 @yuumasato should be ready for another look.

**Comment by rhmdnd** [comment]
/test images

Image registry threw a 500...

**Comment by rhmdnd** [comment]
Applying px, doc, and qe labels since this isn't used anywhere in our upstream build process and shouldn't require any documentation changes.

**Review by yuumasato — APPROVED** [review]
/lgtm

**Comment by rhmdnd** [comment]
Tests here are going to fail until we get https://github.com/ComplianceAsCode/compliance-operator/pull/523 landed.

**Pull request merged**
