### PR TITLE
Release v1.1.0

### PR DESCRIPTION
**Pull request by rhmdnd**

### CODE REVIEW

**Review by jhrozek — APPROVED** [review]
/lgtm

**Comment by jhrozek** [comment]
/hold
in case PR #354 needs to go first

**Comment by rhmdnd** [comment]
> in case PR #354 needs to go first

I had to push the `ocp-1.0` branch changes manually for this PR anyway. So long as the release PR looks good, I think we can move forward without merging #354 (it'll just be ready for the next upstream release).

**Review by Vincent056 — APPROVED** [review]
/lgtm

**Comment by rhmdnd** [comment]
This is good to go in now.

**Comment by sheriff-rh** [comment]
lgtm! :rocket:

**Pull request merged**
