### PR TITLE
Update Workshop instructions and outputs

### PR DESCRIPTION
**Pull request by yuumasato**
- Let's use resources from ComplianceAsCode/compliance-operator
- Fix typoes
- Update link to upstream operator image
- Update links to CaC/content documenation
- Update output of build_ds_container.py

### CODE REVIEW

**Review by rhmdnd — APPROVED** [review]

**Comment by yuumasato** [comment]
I  have just rebased on top of latest master.

**Review by rhmdnd — APPROVED** [review]
/lgtm

**Pull request merged**
