### PR TITLE
[COMPLY-1339] add compare if image equals

### PR DESCRIPTION
**Pull request by muellerfabi**
This commit should fix the bug I noticed: https://issues.redhat.com/browse/COMPLY-1339

### CODE REVIEW

**Comment by rhmdnd** [comment]
Wow - nice find. Thanks for the patch.

It looks like the best way to test this would be to use an upgrade test, where we:

1. Install older version of CO
2. Create a `ScanSettingBinding`
3. Assert the `CronJob` associated with the `ComplianceSuite` is using the correct image
4. Upgrade the operator
5. Assert the `CronJob` associated with the `ComplianceSuite` is not using the old image, but the new operator image

**Comment by muellerfabi** [comment]
> @muellerfabi @rhmdnd I tested it on a connected cluster. I can still see the the Image of the derived Cronjob is the same as before. I don't think it is expected. Could you please help to check? Thanks. I will try to test on a disconnected cluster tomorrow.

I am planning some time tomorrow to check on this.

**Comment by muellerfabi** [comment]
Now the cronjob is getting updated according to the given env var `RELATED_IMAGE_OPERATOR` in operator

**Comment by xiaojiey** [comment]
```
1. Install compliance-operator.v1.1.0
2. Create ssb:
$ oc compliance bind -N test profile/ocp4-cis-node
Creating ScanSettingBinding test
$ oc get suite -w
NAME   PHASE     RESULT
test   RUNNING   NOT-AVAILABLE
test   RUNNING   NOT-AVAILABLE
test   AGGREGATING   NOT-AVAILABLE
test   AGGREGATING   NOT-AVAILABLE
test   DONE          COMPLIANT
test   DONE          COMPLIANT
^C$  oc get suite -o yaml | grep -i contentImage
      contentImage: registry.redhat.io/compliance/openshift-compliance-content-rhel8@sha256:c7a1beb410e1ee3d3c14d6514a5c1b24af84aca3d248f07e058e8f54f92b9634
      contentImage: registry.redhat.io/compliance/openshift-compliance-content-rhel8@sha256:c7a1beb410e1ee3d3c14d6514a5c1b24af84aca3d248f07e058e8f54f
      $ skopeo inspect docker://$(oc get cronjob test-rerunner -ojsonpath={.spec.jobTemplate.spec.template.spec.containers[0].image}) | jq '.Labels.url'l'
"https://access.redhat.com/containers/#/registry.access.redhat.com/openshift-compliance-operator/images/1.1.0-5"
2. Upgrade to newer version(the one in this PR):
$ oc get cronjob test-rerunner -ojsonpath={.spec.jobTemplate.spec.template.spec.containers[0].image}
registry.redhat.io/compliance/openshift-compliance-rhel8-operator@sha256:0f448b6d5ff0210c902fe442648c0f88e0f474624e0911b5516d7008e1158f6f
$ oc patch sub compliance-operator-sub -p '{"spec":{"source":"compliance-operator","channel":"alpha"}}' --type='merge'
subscription.operators.coreos.com/compliance-operator-sub patched
$ oc get ip
NAME            CSV                          APPROVAL    APPROVED
install-vlnvw   compliance-operator.v1.1.0   Automatic   true
install-zkpp6   compliance-operator.v1.2.0   Automatic   true
$ oc get csv -w
NAME                         DISPLAY               VERSION   REPLACES                     PHASE
compliance-operator.v1.1.0   Compliance Operator   1.1.0                                  Replacing
compliance-operator.v1.2.0   Compliance Operator   1.2.0     compliance-operator.v1.1.0   Pending
compliance-operator.v1.2.0   Compliance Operator   1.2.0     compliance-operator.v1.1.0   InstallReady
compliance-operator.v1.2.0   Compliance Operator   1.2.0     compliance-operator.v1.1.0   Installing
compliance-operator.v1.2.0   Compliance Operator   1.2.0     compliance-operator.v1.1.0   Installing
compliance-operator.v1.2.0   Compliance Operator   1.2.0     compliance-operator.v1.1.0   Succeeded
compliance-operator.v1.1.0   Compliance Operator   1.1.0                                  Deleting
compliance-operator.v1.1.0   Compliance Operator   1.1.0                                  Deleting
^C$ oc get pb
NAME     CONTENTIMAGE                                 CONTENTFILE         STATUS
ocp4     ghcr.io/complianceascode/k8scontent:latest   ssg-ocp4-ds.xml     VALID
rhcos4   ghcr.io/complianceascode/k8scontent:latest   ssg-rhcos4-ds.xml   VALID
3. Check the .Labels.url has been updated:
$ oc get suite -o yaml | grep -i contentImage
      contentImage: ghcr.io/complianceascode/k8scontent:latest
      contentImage: ghcr.io/complianceascode/k8scontent:latest
$ skopeo inspect docker://$(oc get cronjob test-rerunner -ojsonpath={.spec.jobTemplate.spec.template.spec.containers[0].image}) | jq '.Labels.url'
"https://access.redhat.com/containers/#/registry.access.redhat.com/ubi9/ubi-micro/images/9.2-13"
```

**Comment by muellerfabi** [comment]
Is there anything that needs to be done from my side to get it merged?

**Comment by xiaojiey** [comment]
/label qe-approved
Sorry, forgot to add the label

**Review by Vincent056 — APPROVED** [review]
/lgtm

**Comment by muellerfabi** [comment]
Rebased

**Comment by rhmdnd** [comment]
Removing the hold since it looks like QE verified the fix.

Adding @sheriff-rh for docs review and @mkumku for PX review.

**Pull request merged**
