### PR TITLE
Add container and repository security scanning

### PR DESCRIPTION
**Pull request by JAORMX**
This adds a workflow that runs Trivy [1] on all Dockerfiles in the repository.

[1] https://aquasecurity.github.io/trivy/

### CODE REVIEW

**Comment by jhrozek** [comment]
This is cool!
One question: should these actions be blocking? I'm wondering if there's a situation where the images are not updated in a timely manner, is this going to block PR merges while we wait for someone to respin the images?

**Comment by JAORMX** [comment]
@jhrozek well, this only reports on fixed vulnerabilities, so I'd say that since we depend on [UBI images directly](https://github.com/ComplianceAsCode/compliance-operator/blob/master/build/Dockerfile#L12), this shouldn't be as problematic. The main issue I see is the must-gather image, which I mentioned in the gitter channel as a problem. I removed the scanning for that one and asked for opinions.

**Comment by jhrozek** [comment]
> @jhrozek well, this only reports on fixed vulnerabilities, so I'd say that since we depend on [UBI images directly](https://github.com/ComplianceAsCode/compliance-operator/blob/master/build/Dockerfile#L12), this shouldn't be as problematic. The main issue I see is the must-gather image, which I mentioned in the gitter channel as a problem. I removed the scanning for that one and asked for opinions.

OK, let's see how it goes. Worst case we can always make the action non-blocking or remove it.

**Review by jhrozek — APPROVED** [review]
/lgtm
/label qe-approved
/label px-approved
/label doc-approved

**Pull request merged**
