### PR TITLE
Add an option to deploy on generic kube

### PR DESCRIPTION
**Pull request by Vincent056**
Update Kustomize and make target to be able to deploy on generic Kubernetes cluster.

run `PLATFORM=generic make deploy-local` to deploy on a generic Kubernetes cluster

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]

**Comment by JAORMX** [comment]
If you wanna deploy in generic kube, you might want to get a helm chart in place as well.

**Comment by Vincent056** [comment]
> If you wanna deploy in generic kube, you might want to get a helm chart in place as well.

Thanks for the advice, I can have that in a separate patch

**Review by rhmdnd — COMMENTED** [review]
Just a few minor comments that we can cleanup in a separate patch. Testing this out on a hypershift cluster now.

**Comment by xiaojiey** [comment]
Tried to verify it. But failed to login to hypershift hosted cluster. Created a Jira ticket to track https://issues.redhat.com/browse/OCPQE-15174

**Comment by xiaojiey** [comment]
@Vincent056 Tried to install compliance operator on a hypershift hosted cluster. The command `PLATFORM=generic make deploy-local` works. The only problem is no profilebinding created. Is it expected behavior? Thanks.
$ PLATFORM=generic make deploy-local
...
/home/xiyuan/securityandcompliance/compliance-operator/build/_tools/kustomize build config/generic | sed -e 's%quay.io/compliance-operator/compliance-operator:latest%image-registry.openshift-image-registry.svc:5000/openshift/compliance-operator:latest%' -e 's%ghcr.io/complianceascode/k8scontent:latest%ghcr.io/complianceascode/k8scontent:latest%' -e 's%quay.io/compliance-operator/openscap-ocp:latest%image-registry.openshift-image-registry.svc:5000/openshift/openscap-ocp:latest%' | kubectl apply -f -
namespace/openshift-compliance unchanged
serviceaccount/api-resource-collector created
serviceaccount/compliance-operator created
serviceaccount/profileparser created
serviceaccount/remediation-aggregator created
serviceaccount/rerunner created
serviceaccount/resultscollector created
serviceaccount/resultserver created
role.rbac.authorization.k8s.io/api-resource-collector created
role.rbac.authorization.k8s.io/compliance-operator created
role.rbac.authorization.k8s.io/leader-election-role created
role.rbac.authorization.k8s.io/profileparser created
role.rbac.authorization.k8s.io/remediation-aggregator created
role.rbac.authorization.k8s.io/rerunner created
role.rbac.authorization.k8s.io/resultscollector created
role.rbac.authorization.k8s.io/resultserver created
clusterrole.rbac.authorization.k8s.io/api-resource-collector created
clusterrole.rbac.authorization.k8s.io/compliance-operator created
clusterrole.rbac.authorization.k8s.io/compliance-operator-metrics created
clusterrole.rbac.authorization.k8s.io/complianceremediation-editor-role created
clusterrole.rbac.authorization.k8s.io/complianceremediation-viewer-role created
clusterrole.rbac.authorization.k8s.io/compliancescan-editor-role created
clusterrole.rbac.authorization.k8s.io/compliancescan-viewer-role created
clusterrole.rbac.authorization.k8s.io/compliancesuite-editor-role created
clusterrole.rbac.authorization.k8s.io/compliancesuite-viewer-role created
clusterrole.rbac.authorization.k8s.io/profilebundle-editor-role created
clusterrole.rbac.authorization.k8s.io/profilebundle-viewer-role created
clusterrole.rbac.authorization.k8s.io/remediation-aggregator created
clusterrole.rbac.authorization.k8s.io/scansettingbinding-editor-role created
clusterrole.rbac.authorization.k8s.io/scansettingbinding-viewer-role created
clusterrole.rbac.authorization.k8s.io/tailoredprofile-editor-role created
clusterrole.rbac.authorization.k8s.io/tailoredprofile-viewer-role created
rolebinding.rbac.authorization.k8s.io/api-resource-collector created
rolebinding.rbac.authorization.k8s.io/compliance-operator created
rolebinding.rbac.authorization.k8s.io/compliance-operator-metrics created
rolebinding.rbac.authorization.k8s.io/leader-election-rolebinding created
rolebinding.rbac.authorization.k8s.io/profileparser created
rolebinding.rbac.authorization.k8s.io/remediation-aggregator created
rolebinding.rbac.authorization.k8s.io/rerunner created
rolebinding.rbac.authorization.k8s.io/resultscollector created
rolebinding.rbac.authorization.k8s.io/resultserver created
clusterrolebinding.rbac.authorization.k8s.io/api-resource-collector created
clusterrolebinding.rbac.authorization.k8s.io/compliance-operator created
clusterrolebinding.rbac.authorization.k8s.io/remediation-aggregator created
deployment.apps/compliance-operator created
$ oc project openshift-compliance
Now using project "openshift-compliance" on server "https://a1f588a6f14dd4ed995d2e72c255c642-7747bb2697841aa1.elb.us-east-2.amazonaws.com:6443".
$ oc get pod
NAME                                  READY   STATUS    RESTARTS   AGE
compliance-operator-5dd499864-5sz2q   1/1     Running   0          9m4s
$ oc get profilebinding 
error: the server doesn't have a resource type "profilebinding"

**Comment by Vincent056** [comment]
> @Vincent056 Tried to install compliance operator on a hypershift hosted cluster. The command `PLATFORM=generic make deploy-local` works. The only problem is no profilebundle created. Is it expected behavior? Thanks. $ PLATFORM=generic make deploy-local ... /home/xiyuan/securityandcompliance/compliance-operator/build/_tools/kustomize build config/generic | sed -e 's%quay.io/compliance-operator/compliance-operator:latest%image-registry.openshift-image-registry.svc:5000/openshift/compliance-operator:latest%' -e 's%ghcr.io/complianceascode/k8scontent:latest%ghcr.io/complianceascode/k8scontent:latest%' -e 's%quay.io/compliance-operator/openscap-ocp:latest%image-registry.openshift-image-registry.svc:5000/openshift/openscap-ocp:latest%' | kubectl apply -f - namespace/openshift-compliance unchanged serviceaccount/api-resource-collector created serviceaccount/compliance-operator created serviceaccount/profileparser created serviceaccount/remediation-aggregator created serviceaccount/rerunner created serviceaccount/resultscollector created serviceaccount/resultserver created role.rbac.authorization.k8s.io/api-resource-collector created role.rbac.authorization.k8s.io/compliance-operator created role.rbac.authorization.k8s.io/leader-election-role created role.rbac.authorization.k8s.io/profileparser created role.rbac.authorization.k8s.io/remediation-aggregator created role.rbac.authorization.k8s.io/rerunner created role.rbac.authorization.k8s.io/resultscollector created role.rbac.authorization.k8s.io/resultserver created clusterrole.rbac.authorization.k8s.io/api-resource-collector created clusterrole.rbac.authorization.k8s.io/compliance-operator created clusterrole.rbac.authorization.k8s.io/compliance-operator-metrics created clusterrole.rbac.authorization.k8s.io/complianceremediation-editor-role created clusterrole.rbac.authorization.k8s.io/complianceremediation-viewer-role created clusterrole.rbac.authorization.k8s.io/compliancescan-editor-role created clusterrole.rbac.authorization.k8s.io/compliancescan-viewer-role created clusterrole.rbac.authorization.k8s.io/compliancesuite-editor-role created clusterrole.rbac.authorization.k8s.io/compliancesuite-viewer-role created clusterrole.rbac.authorization.k8s.io/profilebundle-editor-role created clusterrole.rbac.authorization.k8s.io/profilebundle-viewer-role created clusterrole.rbac.authorization.k8s.io/remediation-aggregator created clusterrole.rbac.authorization.k8s.io/scansettingbinding-editor-role created clusterrole.rbac.authorization.k8s.io/scansettingbinding-viewer-role created clusterrole.rbac.authorization.k8s.io/tailoredprofile-editor-role created clusterrole.rbac.authorization.k8s.io/tailoredprofile-viewer-role created rolebinding.rbac.authorization.k8s.io/api-resource-collector created rolebinding.rbac.authorization.k8s.io/compliance-operator created rolebinding.rbac.authorization.k8s.io/compliance-operator-metrics created rolebinding.rbac.authorization.k8s.io/leader-election-rolebinding created rolebinding.rbac.authorization.k8s.io/profileparser created rolebinding.rbac.authorization.k8s.io/remediation-aggregator created rolebinding.rbac.authorization.k8s.io/rerunner created rolebinding.rbac.authorization.k8s.io/resultscollector created rolebinding.rbac.authorization.k8s.io/resultserver created clusterrolebinding.rbac.authorization.k8s.io/api-resource-collector created clusterrolebinding.rbac.authorization.k8s.io/compliance-operator created clusterrolebinding.rbac.authorization.k8s.io/remediation-aggregator created deployment.apps/compliance-operator created $ oc project openshift-compliance Now using project "openshift-compliance" on server "https://a1f588a6f14dd4ed995d2e72c255c642-7747bb2697841aa1.elb.us-east-2.amazonaws.com:6443". $ oc get pod NAME READY STATUS RESTARTS AGE compliance-operator-5dd499864-5sz2q 1/1 Running 0 9m4s $ oc get pb error: the server doesn't have a resource type "pb"

Could you try with PLATFORM=hypershift make deploy-local for HyperShift deployment

**Comment by xiaojiey** [comment]
Verification pass with command `PLATFORM=hypershift make deploy-local`. It is working as expected.

```
$ PLATFORM=hypershift make deploy-local
make: go: Permission denied
mkdir -p build/_tools
go build -o build/_tools/controller-gen ./vendor/sigs.k8s.io/controller-tools/cmd/controller-gen
/home/xiyuan/securityandcompliance/compliance-operator/build/_tools/controller-gen rbac:roleName=compliance-operator crd webhook paths=./pkg/apis/compliance/v1alpha1 output:crd:artifacts:config=config/crd/bases
podman build -f build/Dockerfile -t quay.io/xiyuan/compliance-operator:0515 .
[1/2] STEP 1/5: FROM golang:1.20 AS builder
[1/2] STEP 2/5: WORKDIR /go/src/github.com/openshift/compliance-operator
--> Using cache 321450432d1a85383e54aa565d5f4dd15f5c8a077622337c15454208fede174d
--> 321450432d1a
[1/2] STEP 3/5: ENV GOFLAGS=-mod=vendor
--> Using cache 3c8ac1a7c4c7d8107b45295771cfb21e520b5bf5f180367eb219f7131fb68488
--> 3c8ac1a7c4c7
[1/2] STEP 4/5: COPY . . 
--> 0383c4de6795
[1/2] STEP 5/5: RUN make manager
...
rolebinding.rbac.authorization.k8s.io/api-resource-collector created
rolebinding.rbac.authorization.k8s.io/compliance-operator created
rolebinding.rbac.authorization.k8s.io/compliance-operator-metrics created
rolebinding.rbac.authorization.k8s.io/leader-election-rolebinding created
rolebinding.rbac.authorization.k8s.io/profileparser created
rolebinding.rbac.authorization.k8s.io/remediation-aggregator created
rolebinding.rbac.authorization.k8s.io/rerunner created
rolebinding.rbac.authorization.k8s.io/resultscollector created
rolebinding.rbac.authorization.k8s.io/resultserver created
...
$ oc get pod
NAME                                             READY   STATUS    RESTARTS   AGE
compliance-operator-645dc6c4b7-xxk5q             1/1     Running   0          2m28s
ocp4-openshift-compliance-pp-59c779767b-d8c9r    1/1     Running   0          2m22s
rhcos4-openshift-compliance-pp-bf4f7677d-7m5f2   1/1     Running   0          2m22s
$ oc get pod
NAME                                             READY   STATUS    RESTARTS   AGE
compliance-operator-645dc6c4b7-xxk5q             1/1     Running   0          2m28s
ocp4-openshift-compliance-pp-59c779767b-d8c9r    1/1     Running   0          2m22s
rhcos4-openshift-compliance-pp-bf4f7677d-7m5f2   1/1     Running   0          2m22s

```

**Review by rhmdnd — APPROVED** [review]
/lgtm

Works for me on Hypershift environments!

**Comment by Vincent056** [comment]
Adding gpg signature

**Pull request merged**
