### PR TITLE
Fix deployment on OCP 4.6

### PR DESCRIPTION
**Pull request by mrogers950**
Check against changing the Service's clusterIP, and retain the existing value as OCP 4.6 does not tolerate that. Later versions just ignore the field.

### CODE REVIEW

**Review by jhrozek — APPROVED** [review]
/lgtm

**Comment by jhrozek** [comment]
Nothing to document or no support impact, but let's have qe approve the PR.

**Comment by xiaojiey** [comment]
/label qe-approved
 Without the pr, the operator installation will fail due to `"Error creating metrics service/secret","error":"Service \"metrics\" is invalid: spec.clusterIP: Invalid value: \"\": field is immutable","stacktrace""`; with the pr, the installation will succeeded.
 Test details seen from: http://pastebin.test.redhat.com/1075104
```
 $ oc get clusterversion
NAME      VERSION                             AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.6.0-0.nightly-2022-09-20-111416   True        False         96m     Cluster version is 4.6.0-0.nightly-2022-09-20-111416
$  make images && make push
...
$ make catalog && make catalog-deploy
make: go: Permission denied
/usr/local/bin/opm index add --container-tool podman --mode semver --tag quay.io/xiyuan/compliance-operator-catalog:0926 --bundles quay.io/xiyuan/compliance-operator-bundle:0926 
...
podman push quay.io/xiyuan/compliance-operator-catalog:0926
...
$ oc get sub
NAME                      PACKAGE               SOURCE                CHANNEL
compliance-operator-sub   compliance-operator   compliance-operator   alpha

$ oc get sub
NAME                      PACKAGE               SOURCE                CHANNEL
compliance-operator-sub   compliance-operator   compliance-operator   alpha
$ oc get ip
NAME            CSV                           APPROVAL    APPROVED
install-bzxll   compliance-operator.v0.1.55   Automatic   true
$ oc get csv
NAME                          DISPLAY               VERSION   REPLACES   PHASE
compliance-operator.v0.1.55   Compliance Operator   0.1.55               Succeeded
$ oc get pod
NAME                                              READY   STATUS    RESTARTS   AGE
compliance-operator-78dbd98fc8-b9q6c              1/1     Running   1          5m15s
ocp4-openshift-compliance-pp-75dc6b78-d7vpv       1/1     Running   0          4m57s
rhcos4-openshift-compliance-pp-548f8f8586-tlhkb   1/1     Running   0          4m57s
```

**Pull request merged**
