### PR TITLE
Update crds.md

### PR DESCRIPTION
**Pull request by jhrozek**
This was proposed against the old repo as https://github.com/openshift/compliance-operator/pull/828 so I'm submitting the same PR on behalf of the author.

### CODE REVIEW

**Comment by jhrozek** [comment]
rebased atop current master so that e2e picks up the latest content patches

**Comment by jhrozek** [comment]
/test e2e-aws
cluster installations are very broken

**Comment by jhrozek** [comment]
@Vincent056 @rhmdnd PTAL

**Review by Vincent056 — APPROVED** [review]
/lgtm

**Pull request merged**
