### PR TITLE
NOSUBMIT: Disable TestTolerations to see if e2e passes

### PR DESCRIPTION
**Pull request by jhrozek**
Just checking if we get a clean e2e run with the test disabled

### CODE REVIEW

**Comment by jhrozek** [comment]
/hold 
this is just a test PR

**Comment by jhrozek** [comment]
we can't test an e2e patch without a cluster :-)
/retest

**Comment by rhmdnd** [comment]
> we can't test an e2e patch without a cluster :-)

Yesterday, I noticed quite a few of our E2E failures were due to AWS issues. Still unclear if or when those will get ironed out.

**Comment by jhrozek** [comment]
> 

Well, this passed. I'll close and reopen the PR to force the test to see if the test didn't just pass by accident.

**Comment by jhrozek** [comment]
Closing in favour of #113

**Pull request closed without merging**
