### PR TITLE
Change image repo CO uses

### PR DESCRIPTION
**Pull request by Vincent056**
Change the image repo CO uses from quay to ghcr, we need to wait for https://github.com/ComplianceAsCode/compliance-operator/pull/263 to merge.

### CODE REVIEW

**Comment by Vincent056** [comment]
We also need to wait for https://github.com/ComplianceAsCode/compliance-operator/pull/270 to merge, so we can have the test content ready

**Comment by rhmdnd** [comment]
/retest

Since it looks like the required patches merged.

**Review by rhmdnd — APPROVED** [review]

**Comment by rhmdnd** [comment]
Adding other required labels since this is specific to upstream maintenance and testing.

**Pull request merged**
