### PR TITLE
Update bundle files

### PR DESCRIPTION
**Pull request by Vincent056**
This is to fix failures in the `verify-bundle` workflow.

### CODE REVIEW

**Comment by Vincent056** [comment]
a side note should we ignore text formate changes?  @rhmdnd

**Review by rhmdnd — APPROVED** [review]
/lgtm

**Comment by rhmdnd** [comment]
The ROSA e2e failures are due to issues waiting for the cluster operators to become available. See them across other tests that are using the same environments. I don't think it's related to this change.

**Pull request merged**
