### PR TITLE
Release v0.1.54

### PR DESCRIPTION
**Pull request by mrogers950**

### CODE REVIEW

**Review by Vincent056 — APPROVED** [review]
/lgtm

**Comment by Vincent056** [comment]
Thanks for doing a release!

**Comment by mrogers950** [comment]
https://github.com/ComplianceAsCode/compliance-operator/runs/8252558351?check_suite_focus=true has failed (the manager unit tests) only on the Z build. Should we override this job?

**Comment by mrogers950** [comment]
Adding acks since this PR is just a formality and not a feature.

/label qe-approved
/label docs-approved
/label px-approved

**Pull request merged**
